# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: no-commit-to-branch
      args: [--branch, staging, --branch, main]

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.6
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]

-   repo: https://github.com/asottile/blacken-docs
    rev: 1.19.1
    hooks:
    -   id: blacken-docs

- repo: https://github.com/srstevenson/nb-clean
  rev: 4.0.1
  hooks:
    - id: nb-clean
      args:
        - --remove-empty-cells
        - --preserve-cell-outputs
        - --preserve-execution-counts
        - --preserve-cell-metadata
        - tags
        - slideshow
        - --
