language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pytest
notifications:
  email:
    recipients:
      - your.email@somewhere.com
    on_success: change
    on_failure: change
