branches:
  only:
    - master

os:
  - linux
  - osx

language: python

python:
  - "3.6"
  - "3.7"

install:
  - virtualenv devenv
  - source devenv/bin/activate
  - pip3 install -r requirements.txt
  - pre-commit install

script:
  - pre-commit run --all-files
  - pytest .

notifications:
  email:
    recipients:
      - your.email@somewhere.com
    on_success: change
    on_failure: change
