name: blank-project
channels:
  - conda-forge

platforms:
  - win-64
  - linux-64
  - osx-64

dependencies:
  # Core
  - python={{ get_env("PY", default="3.11") }}
  - ruff
  - numpy>=1.13.3
  - pytest>=3.8.0
  - scipy>=1.1.0
  - mypy
  - invoke
  - rich
  - conda-lock

  # For tests
  - pytest>=3.8.0
  - pytest-cov
  - pytest-xdist
  - coverage

  # For documentation
  - mkdocs
  - mkdocs-material
  - mkdocstrings-python

  # Hooks for git
  - pre-commit

environment:
  PYTHONPATH:
    - {{ root }}/src
