name: blank-project
channels:
  - conda-forge

dependencies:
  # Python stack
  - python={{ get_env("PY", default="3.11") }}
  - ruff
  - numpy>=1.13.3
  - pytest>=3.8.0
  - scipy>=1.1.0
  - mypy
  - invoke
  - rich

  # For tests
  - pytest>=3.8.0
  - pytest-cov
  - pytest-xdist

  # For documentation
  - mkdocs
  - mkdocs-material
  - mkdocstrings-python

  # Hooks for git
  - pre-commit

environment:
  PYTHONPATH:
    - {{ root }}/src
