site_name: mypackage's Docs
site_description: A simple MkDocs demonstration
site_url: https://volpatto.github.io/blank-python-project/
site_author: Author's name
repo_url: https://github.com/volpatto/blank-python-project

theme:
  name: "material"
  custom_dir: docs/overrides
  icon:
    repo: octicons/mark-github-24
  features:
    - navigation.instant
    - content.code.copy
  palette:
    - scheme: default
      # Toggle buttom dark mode
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      # Toggle buttom light mode
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - css/nb-prompts.css  # a trick to hide `In [#]/Out [#]` in ipynb cells

markdown_extensions:
  - toc:
      permalink: true

plugins:
  - search
  - monorepo
  - mkdocstrings:
      handlers:
            python:
              paths: [src]
              options:
                docstring_style: sphinx
  - mkdocs-jupyter:
      include: ["**/*.ipynb"]
      execute: false
      include_requirejs: true
      include_source: True
      ignore_h1_titles: True  # Disable this if you want to get page title from h1 header in ipynb

# Define the navigation bar
nav:
  - Home: index.md
  - API Reference: reference.md
  - Notebooks:
    - Overview: notebooks.md
    - Tutorials: '!include ./notebooks/mkdocs.yml'
