site_name: mypackage's Docs

theme:
  name: "material"

plugins:
  - mkdocstrings:
      handlers:
            python:
              paths: [src]
              options:
                docstring_style: sphinx

# Define the navigation bar
nav:
  - Home: index.md
  - API Reference: reference.md

repo_url: https://github.com/volpatto/blank-python-project
