name: Automerge PR

on:
  pull_request:
    types: [labeled, synchronize, opened]
    branches:
      - main

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    # Only run if the PR has the "automerge" label
    if: contains(github.event.pull_request.labels.*.name, 'automerge')

    steps:
      - name: Wait for all status checks to pass
        uses: pascalgn/automerge-action@v0.15.4
        env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
            MERGE_METHOD: "squash"
            MERGE_REQUIRED_APPROVALS: "0"  # add the minimal number of reviewers here
            MERGE_RETRY_SLEEP: "60000"  # time to wait to merge in miliseconds (current: 1 min)
            MERGE_RETRIES: "10"  # The number of retries between each MERGE_RETRY_SLEEP.
                                 # Current: after each minute (since MERGE_RETRY_SLEEP: "60000"),
                                 # the job will check the PR and see if it is ready to go with
                                 # all checks passing. With the current settings, this step will
                                 # wait a total of 10 minutes.
