name: devenv

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  schedule:
  - cron: "0 5 * * 1"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          conda-channels: conda-forge
      - run: conda --version
      - name: Configure conda-devenv
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda install conda-devenv
          conda update -q conda
          conda info -a
          conda devenv
          source activate blank-project
      - name: pre-commit Checkers and Formatters
        run: |
          pre-commit install
          pre-commit run --all-files
      - name: Test with pytest
        run: |
          pytest . --cov-config=.coveragerc --cov-report=xml --cov=mypackage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.xml
